package com.quibbly

object Keys {
    const val IS_DEBUG = "IS_DEBUG"
    const val WEB_CLIENT_ID = "WEB_CLIENT_ID"
    const val ANDROID_WEB_CLIENT_ID_DEV = "ANDROID_WEB_CLIENT_ID_DEV"
    const val IOS_WEB_CLIENT_ID_DEV = "IOS_WEB_CLIENT_ID_DEV"
    const val ANDROID_WEB_CLIENT_ID_PROD = "ANDROID_WEB_CLIENT_ID_PROD"
    const val IOS_WEB_CLIENT_ID_PROD = "IOS_WEB_CLIENT_ID_PROD"
    const val MAP_KEY = "MAP_KEY"
    const val ANDROID_MAP_KEY_DEV = "ANDROID_MAP_KEY_DEV"
    const val ANDROID_MAP_KEY_PROD = "ANDROID_MAP_KEY_PROD"
    const val IOS_MAP_KEY_DEV = "IOS_MAP_KEY_DEV"
    const val IOS_MAP_KEY_PROD = "IOS_MAP_KEY_PROD"
}